--2. házi feladat
USE Webshop;
GO

CREATE TABLE dbo.UGYFEL_MASZKOLT
(
    [LOGIN] VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) MASKED WITH (FUNCTION = 'email()') NOT NULL,
    NEV VARCHAR(64) MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",0)') NOT NULL,
    SZULEV NUMERIC(4) MASKED WITH (FUNCTION = 'random(1900,2024)') NULL,
    NEM VARCHAR(1),
    CIM VARCHAR(128)
);
GO

INSERT INTO dbo.UGYFEL_MASZKOLT (LOGIN, EMAIL, NEV, SZULEV, NEM, CIM)
SELECT LOGIN, EMAIL, NEV, SZULEV, NEM, CIM
FROM dbo.UGYFEL;
GO

--Felhasználó létrehozása
CREATE USER MaszkoltUgyfel WITHOUT LOGIN;
GO

GRANT SELECT ON dbo.UGYFEL_MASZKOLT TO MaszkoltUgyfel;
GO
